# My Neural Network

In [1]:
# import the neccessary libraries
import numpy as np
import pandas  as pd
from one_neuron import NeuralNetwork

In [2]:
# read in the data
train = pd.read_csv("../assignments/data/titanic_train.csv")
test  = pd.read_csv("../assignments/data/titanic_test.csv")

In [3]:
# list the columns that are most likely to affect chance of survival
features = ["Pclass", "Sex", "SibSp", "Parch", "Embarked"]

# seperate the training data from the classes/labels and
# convert categorical variable into dummy/indicator variables
x_train, y_train = pd.get_dummies(train[features]), train["Survived"]
x_test = pd.get_dummies(test[features])

In [4]:
# create a model
model = NeuralNetwork()

In [5]:
# train the model
model.fit(x_train, y_train, epochs = 4000)

0000/4000 [........................................] - mse: 202.55
0100/4000 [=.......................................] - mse: 191.02
0200/4000 [==......................................] - mse: 179.87
0300/4000 [===.....................................] - mse: 171.91
0400/4000 [====....................................] - mse: 167.82
0500/4000 [=====...................................] - mse: 167.57
0600/4000 [======..................................] - mse: 163.74
0700/4000 [=======.................................] - mse: 159.77
0800/4000 [========................................] - mse: 156.96
0900/4000 [=========...............................] - mse: 156.04
1000/4000 [==========..............................] - mse: 153.77
1100/4000 [===========.............................] - mse: 151.33
1200/4000 [============............................] - mse: 149.96
1300/4000 [=============...........................] - mse: 147.88
1400/4000 [==============..........................] - mse: 146.70
1500/4000 [===============.........................] - mse: 146.20
1600/4000 [================........................] - mse: 144.46
1700/4000 [=================.......................] - mse: 143.23
1800/4000 [==================......................] - mse: 143.02
1900/4000 [===================.....................] - mse: 144.46
2000/4000 [====================....................] - mse: 142.78
2100/4000 [=====================...................] - mse: 142.42
2200/4000 [======================..................] - mse: 140.68
2300/4000 [=======================.................] - mse: 139.43
2400/4000 [========================................] - mse: 138.72
2500/4000 [=========================...............] - mse: 138.54
2600/4000 [==========================..............] - mse: 137.67
2700/4000 [===========================.............] - mse: 137.24
2800/4000 [============================............] - mse: 137.37
2900/4000 [=============================...........] - mse: 137.06
3000/4000 [==============================..........] - mse: 136.40
3100/4000 [===============================.........] - mse: 136.00
3200/4000 [================================........] - mse: 135.61
3300/4000 [=================================.......] - mse: 135.26
3400/4000 [==================================......] - mse: 134.92
3500/4000 [===================================.....] - mse: 134.73
3600/4000 [====================================....] - mse: 134.11
3700/4000 [=====================================...] - mse: 133.70
3800/4000 [======================================..] - mse: 133.75
3900/4000 [=======================================.] - mse: 133.19

In [16]:
# make predictions on the test data
preds = model.predict(x_test)
preds[:5]

array([[0.27803245],
       [0.54365681],
       [0.39552254],
       [0.14602908],
       [0.53140618]])

In [17]:
# convert the predictions into binary classes
preds = (preds > 0.5) * 1
preds[:5]

array([[0],
       [1],
       [0],
       [0],
       [1]])

# Compare My Model with Tensorflow

In [18]:
import tensorflow as tf

In [19]:
tf_model = tf.keras.Sequential([
  # input layer
  tf.keras.layers.Dense(50, input_dim = x_train.shape[1], activation = "relu"),
  # output layer, with one neuron
  tf.keras.layers.Dense(1, activation = "relu")
])

In [20]:
tf_model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_2 (Dense)             (None, 50)                450

 dense_3 (Dense)             (None, 1)                 51

=================================================================
Total params: 501
Trainable params: 501
Non-trainable params: 0
_________________________________________________________________

In [21]:
# compile the model
tf_model.compile(loss = "binary_crossentropy", optimizer = "adam", metrics = ["accuracy"])

In [22]:
# train the model
tf_model.fit(x_train, y_train, epochs = 20, validation_split = 0.1)

Epoch 1/20
26/26 [==============================] - 1s 8ms/step - loss: 0.7131 - accuracy: 0.6330 - val_loss: 0.5913 - val_accuracy: 0.6222
Epoch 2/20
26/26 [==============================] - 0s 3ms/step - loss: 0.5822 - accuracy: 0.7066 - val_loss: 0.5255 - val_accuracy: 0.7556
Epoch 3/20
26/26 [==============================] - 0s 3ms/step - loss: 0.5301 - accuracy: 0.7728 - val_loss: 0.5120 - val_accuracy: 0.8111
Epoch 4/20
26/26 [==============================] - 0s 4ms/step - loss: 0.5326 - accuracy: 0.7728 - val_loss: 0.4954 - val_accuracy: 0.7667
Epoch 5/20
26/26 [==============================] - 0s 4ms/step - loss: 0.4987 - accuracy: 0.7953 - val_loss: 0.4765 - val_accuracy: 0.8000
Epoch 6/20
26/26 [==============================] - 0s 4ms/step - loss: 0.4881 - accuracy: 0.7903 - val_loss: 0.4761 - val_accuracy: 0.7889
Epoch 7/20
26/26 [==============================] - 0s 3ms/step - loss: 0.4755 - accuracy: 0.7940 - val_loss: 0.4555 - val_accuracy: 0.7889
Epoch 8/20
26/26 [==============================] - 0s 3ms/step - loss: 0.4744 - accuracy: 0.7903 - val_loss: 0.4552 - val_accuracy: 0.8000
Epoch 9/20
26/26 [==============================] - 0s 4ms/step - loss: 0.4863 - accuracy: 0.7928 - val_loss: 0.4587 - val_accuracy: 0.8000
Epoch 10/20
26/26 [==============================] - 0s 3ms/step - loss: 0.4781 - accuracy: 0.8040 - val_loss: 0.4447 - val_accuracy: 0.8000
Epoch 11/20
26/26 [==============================] - 0s 4ms/step - loss: 0.4643 - accuracy: 0.7965 - val_loss: 0.4419 - val_accuracy: 0.8000
Epoch 12/20
26/26 [==============================] - 0s 3ms/step - loss: 0.4786 - accuracy: 0.7953 - val_loss: 0.4270 - val_accuracy: 0.8000
Epoch 13/20
26/26 [==============================] - 0s 3ms/step - loss: 0.4848 - accuracy: 0.8002 - val_loss: 0.4204 - val_accuracy: 0.8000
Epoch 14/20
26/26 [==============================] - 0s 4ms/step - loss: 0.4612 - accuracy: 0.8015 - val_loss: 0.4219 - val_accuracy: 0.8000
Epoch 15/20
26/26 [==============================] - 0s 3ms/step - loss: 0.4530 - accuracy: 0.8015 - val_loss: 0.4286 - val_accuracy: 0.8000
Epoch 16/20
26/26 [==============================] - 0s 3ms/step - loss: 0.4652 - accuracy: 0.8040 - val_loss: 0.4168 - val_accuracy: 0.8000
Epoch 17/20
26/26 [==============================] - 0s 3ms/step - loss: 0.4627 - accuracy: 0.8015 - val_loss: 0.4543 - val_accuracy: 0.8111
Epoch 18/20
26/26 [==============================] - 0s 4ms/step - loss: 0.4642 - accuracy: 0.8102 - val_loss: 0.4237 - val_accuracy: 0.8000
Epoch 19/20
26/26 [==============================] - 0s 4ms/step - loss: 0.4563 - accuracy: 0.8102 - val_loss: 0.4159 - val_accuracy: 0.8000
Epoch 20/20
26/26 [==============================] - 0s 3ms/step - loss: 0.4489 - accuracy: 0.8052 - val_loss: 0.4139 - val_accuracy: 0.8000

In [23]:
# get the predictions
tf_preds = tf_model.predict(x_test)
# convert the predictions into binary classes
tf_preds = (tf_preds > 0.5) * 1

14/14 [==============================] - 0s 1ms/step

In [24]:
def highlight(s):
  """Highlight rows that have different values."""
  if not np.equal(s.nn, s.tf):
    return ["background-color: darkturquoise"] * len(s)
  else:
    return ["background-color: default"] * len(s)

In [25]:
# show a side by side comparison
df = pd.DataFrame({"nn" : preds.ravel(), "tf" : tf_preds.ravel()})
df.style.apply(highlight, axis=1)